windows:
  hosts:
  children:
    servers:
      hosts:
        10.0.5.5:
          hostname: blue10-dc
  vars:
    ansible_user: deployer
    device: Ethernet0
    netmask: 255.255.255.0
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue10.local
    ansible_shell_type: powershell
