all:
  hosts:
  children:
    servers:
      hosts:
        10.0.5.5:
          hostname: blue10-dc
        10.0.5.6:
          hostname: blue10-fs
      vars:
        domain_ou_path: 'OU=servers,OU=Computers,DC=blue10,DC=local'

    workstations:
      hosts:
        10.0.5.85:
          hostname: wks-1
        10.0.5.86:
          hostname: wks-2
      vars:
        domain_ou_path: 'OU=workstations,OU=Computers,DC=blue10,DC=local'
  vars:
    ansible_user: deployer
    device: Ethernet0
    netmask: 255.255.255.0
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue10.local
    ansible_shell_type: powershell
    base_dc: blue10
